 export const elements = {
  svgPath:  '.bg-path',
  nav: '.nav',
  tabHolder: '.tabs',
  tabItems: '.tabs li',
  tab: '.tab',
  tablet: '.tablet',
  formContainer: '.services__container',
  formHolder: '.services__holder',
  carrierForm: '#form-carrier',
  imeiForm: '#form-imei',
  unlockingForm: '#form-unlocking',
  iphoneCarrier: '.form__carrier--iphone',
  iphoneUnlock: '.form__unlock--iphone',
  ipadCarrier: '.form__carrier--ipad',
  ipadUnlock: '.form__unlock--ipad',
  carrierPhone: '.carrier-phone',
  carrierModel: '.carrier-model',
  carrierNetwork: '.carrier-network',
  carrierImei: '#carrier-imei',
  imeiNetwork: '.imei-network',
  imeiImei: '#imei-imei',
  unlockingPhone: '.unlocking-phone',
  unlockingModel: '.unlocking-model',
  unlockingNetwork: '.unlocking-network',
  unlockingImei: '#unlocking-imei',
  payment: '.payment',
  cancelPayment: '.btn-cancel',
  paymentPrice: '.payment__price',
  paymentItems: '.payment__items'
};