 export const elements = {
   svgPath:  '.bg-path',
   nav: '.nav',
   tabHolder: '.tabs',
   tabItems: '.tabs li',
   tab: '.tab',
   tablet: '.tablet',
   formContainer: '.services__container',
   formHolder: '.services__holder',
   carrierForm: '#form-carrier',
   imeiForm: '#form-imei',
   unlockingForm: '#form-unlocking',
   carrierPhone: '.carrier-phone',
  carrierModel: '.carrier-model',
  carrierNetwork: '.carrier-network',
  carrierImei: '#carrier-imei',
  imeiNetwork: '.imei-network',
  imeiImei: '#imei-imei',
  unlockingPhone: '.unlocking-phone',
  unlockingModel: '.unlocking-model',
  unlockingNetwork: '.unlocking-network',
  unlockingImei: '#unlocking-imei',  
};